/* Generated By:JavaCC: Do not edit this line. Parser.java */
package proj.parser;

import proj.ast.*;
import proj.*;
import proj.types.*;
import proj.errors.*;
import proj.env.*;

import java.util.*;

public class Parser implements ParserConstants {

  static final public ASTNode Start() throws ParseException {
  ASTNode t;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 0:
      jj_consume_token(0);
           {if (true) return null;}
      break;
    case LET:
    case Bool:
    case LinBool:
    case MINUS:
    case LPAR:
    case LRPAR:
    case QUESTION:
    case QUESTIONTYPES:
    case NOT:
    case IF:
    case PRINT:
    case PRINTLN:
    case FN:
    case LFN:
    case FST:
    case SND:
    case MATCH:
    case TYPE:
    case TINT:
    case TBOOL:
    case TLBOOL:
    case TSTRING:
    case TUNION:
    case TLUNION:
    case TLINT:
    case SPLIT:
    case LABEL:
    case LLABEL:
    case String:
    case Id:
    case LinNum:
    case Num:
      t = Let();
      jj_consume_token(TERM);
                       {if (true) return t;}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode Let() throws ParseException {
  Token n;
  ASTNode t, e1, e2;
  ASTType t1 = null;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Bool:
    case LinBool:
    case MINUS:
    case LPAR:
    case LRPAR:
    case QUESTION:
    case QUESTIONTYPES:
    case NOT:
    case IF:
    case PRINT:
    case PRINTLN:
    case FN:
    case LFN:
    case FST:
    case SND:
    case MATCH:
    case TINT:
    case TBOOL:
    case TLBOOL:
    case TSTRING:
    case TUNION:
    case TLUNION:
    case TLINT:
    case SPLIT:
    case LABEL:
    case LLABEL:
    case String:
    case Id:
    case LinNum:
    case Num:
      t = Seq();
      break;
    case LET:
       List<Bind> decls  = new ArrayList<Bind>();
      label_1:
      while (true) {
        jj_consume_token(LET);
        n = jj_consume_token(Id);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COLON:
          jj_consume_token(COLON);
          t1 = Type();
          break;
        default:
          jj_la1[1] = jj_gen;
          ;
        }
        jj_consume_token(EQUAL);
        e1 = BA();
        jj_consume_token(SEMIC);
        decls.add(new Bind(n.image, t1, e1)); t1 = null;
        if (jj_2_1(2)) {
          ;
        } else {
          break label_1;
        }
      }
      e2 = Let();
                     t = new ASTLet(decls, e2);
      break;
    case TYPE:
        HashMap<String,ASTType> lbl = new HashMap<String,ASTType>();
      label_2:
      while (true) {
        jj_consume_token(TYPE);
        n = jj_consume_token(Id);
        jj_consume_token(EQUAL);
        t1 = Type();
        jj_consume_token(SEMIC);
        if (lbl.containsKey(n.image)) { {if (true) throw new ParseException("duplicate id");} } else { lbl.put(n.image, t1); }
        if (jj_2_2(2)) {
          ;
        } else {
          break label_2;
        }
      }
      e2 = Let();
                     t = new ASTTypeDef(lbl, e2);
      break;
    default:
      jj_la1[2] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode Seq() throws ParseException {
 Token op;
  ASTNode t1, t2;
    t1 = SeqExp();
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SEMIC:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      op = jj_consume_token(SEMIC);
      t2 = SeqExp();
                 t1 = new ASTSeq(t1, t2);
    }
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode SeqExp() throws ParseException {
 Token op;
  ASTNode t1, t2, t;
    t1 = Check();
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode Check() throws ParseException {
  ASTNode t1, t2;
  ASTType tt1, tt2;
    if (jj_2_3(2147483647)) {
      tt1 = Type();
      jj_consume_token(QUESTIONTYPES);
      tt2 = Type();
                                                t1 = new ASTCheckTypes(tt1, tt2);
    } else if (jj_2_4(2147483647)) {
      t1 = BA();
      jj_consume_token(QUESTION);
      t2 = BA();
                                     t1 = new ASTCheck(t1, t2);
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case Bool:
      case LinBool:
      case MINUS:
      case LPAR:
      case LRPAR:
      case QUESTION:
      case QUESTIONTYPES:
      case NOT:
      case IF:
      case PRINT:
      case PRINTLN:
      case FN:
      case LFN:
      case FST:
      case SND:
      case MATCH:
      case SPLIT:
      case LABEL:
      case LLABEL:
      case String:
      case Id:
      case LinNum:
      case Num:
        t1 = BA();
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
      {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode BA() throws ParseException {
 Token op;
  ASTNode t1, t2;
    t1 = BM();
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case OR:
        ;
        break;
      default:
        jj_la1[5] = jj_gen;
        break label_4;
      }
      op = jj_consume_token(OR);
      t2 = BM();
     t1 = new ASTLogicOp(t1, t2, "||");
    }
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode BM() throws ParseException {
 Token op;
  ASTNode t1, t2;
    t1 = Rel();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case AND:
        ;
        break;
      default:
        jj_la1[6] = jj_gen;
        break label_5;
      }
      op = jj_consume_token(AND);
      t2 = Rel();
                 t1 = new ASTLogicOp(t1, t2, "&&");
    }
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode Rel() throws ParseException {
 Token op;
  ASTNode t1, t2;
    t1 = Exp();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQ:
    case GT:
    case LT:
    case GTEQ:
    case LTEQ:
    case DIF:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EQ:
        op = jj_consume_token(EQ);
        break;
      case GT:
        op = jj_consume_token(GT);
        break;
      case LT:
        op = jj_consume_token(LT);
        break;
      case GTEQ:
        op = jj_consume_token(GTEQ);
        break;
      case LTEQ:
        op = jj_consume_token(LTEQ);
        break;
      case DIF:
        op = jj_consume_token(DIF);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      t2 = Exp();
      t1 = new ASTCmpOp(t1, t2, op.image);
      break;
    default:
      jj_la1[8] = jj_gen;
      ;
    }
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode Exp() throws ParseException {
  Token op;
  ASTNode t1, t2;
    t1 = Term();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        op = jj_consume_token(PLUS);
        break;
      case MINUS:
        op = jj_consume_token(MINUS);
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      t2 = Term();
                  t1 = new ASTArithOp(t1,t2,op.image);
    }
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode Term() throws ParseException {
 Token op, n;
  ASTNode t1, t2;
  ASTType tt1, tt2;
    t1 = Fact();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STAR:
      case DIV:
      case LPAR:
      case LRPAR:
        ;
        break;
      default:
        jj_la1[11] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case STAR:
        jj_consume_token(STAR);
        t2 = Fact();
                            t1 = new ASTArithOp(t1,t2,"*");
        break;
      case DIV:
        jj_consume_token(DIV);
        t2 = Fact();
                                      t1 = new ASTArithOp(t1,t2,"/");
        break;
      case LRPAR:
        jj_consume_token(LRPAR);
               t1 = new ASTApp(t1, new ASTUnit());
        break;
      case LPAR:
        jj_consume_token(LPAR);
        t2 = Let();
        jj_consume_token(RPAR);
                                t1 = new ASTApp(t1, t2);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
       {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode Fact() throws ParseException {
  Token n, n2;
  ASTNode t, e1, e2, t2;
  List<Bind> decls;
  ASTNode body, alt;
  ASTFunc tf, tc, tn;
  ASTLFunc ltf, ltc, ltn;
  ASTType type, type2;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case Num:
      n = jj_consume_token(Num);
                t = new ASTInt(Integer.parseInt(n.image));
      break;
    case LinNum:
      n = jj_consume_token(LinNum);
                   t = new ASTLInt(Integer.parseInt(n.image.substring(0, n.image.length()-1)));
      break;
    case Bool:
      n = jj_consume_token(Bool);
                 t = new ASTBool(Boolean.parseBoolean(n.image));
      break;
    case LinBool:
      n = jj_consume_token(LinBool);
                    t = new ASTLBool(Boolean.parseBoolean(n.image.substring(0, n.image.length()-1)));
      break;
    case Id:
      n = jj_consume_token(Id);
                 t = new ASTId(n.image);
      break;
    case String:
      n = jj_consume_token(String);
                   t = new ASTString(n.image.substring(1, n.image.length()-1));
      break;
    case LRPAR:
      jj_consume_token(LRPAR);
                t = new ASTUnit();
      break;
    case MINUS:
      jj_consume_token(MINUS);
      t = Fact();
                         t = new ASTArithOp(new ASTInt(0), t, "-u");
      break;
    case NOT:
      jj_consume_token(NOT);
      t = Fact();
                       t = new ASTLogicOp(new ASTBool(true), t, "~");
      break;
    case IF:
      jj_consume_token(IF);
      t = BA();
      jj_consume_token(LBRA);
      e1 = Let();
      jj_consume_token(RBRA);
      jj_consume_token(ELSE);
      jj_consume_token(LBRA);
      e2 = Let();
      jj_consume_token(RBRA);
                                                                         t = new ASTIf(t, e1, e2);
      break;
    case FN:
      jj_consume_token(FN);
      n = jj_consume_token(Id);
      jj_consume_token(COLON);
      type = Type();
                                          tf = new ASTFunc(n.image, null, type); tc = tf;
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[13] = jj_gen;
          break label_8;
        }
        jj_consume_token(COMMA);
        n = jj_consume_token(Id);
        jj_consume_token(COLON);
        type = Type();
                                                          tn = new ASTFunc(n.image, null, type); tc.setBody(tn); tc = tn;
      }
      jj_consume_token(ARROW);
      jj_consume_token(LBRA);
      e2 = Let();
      jj_consume_token(RBRA);
                                                             tc.setBody(e2); t = tf;
      break;
    case LFN:
      jj_consume_token(LFN);
      n = jj_consume_token(Id);
      jj_consume_token(COLON);
      type = Type();
                                           ltf = new ASTLFunc(n.image, null, type); ltc = ltf;
      label_9:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[14] = jj_gen;
          break label_9;
        }
        jj_consume_token(COMMA);
        n = jj_consume_token(Id);
        jj_consume_token(COLON);
        type = Type();
                                                          ltn = new ASTLFunc(n.image, null, type); ltc.setBody(ltn); ltc = ltn;
      }
      jj_consume_token(DLOLLIPOP);
      jj_consume_token(LBRA);
      e2 = Let();
      jj_consume_token(RBRA);
                                                                 ltc.setBody(e2); t = ltf;
      break;
    case PRINT:
      jj_consume_token(PRINT);
      t = Fact();
                         t = new ASTPrint(t, false);
      break;
    case PRINTLN:
      jj_consume_token(PRINTLN);
      t = Fact();
                           t = new ASTPrint(t, true);
      break;
    case FST:
      jj_consume_token(FST);
      jj_consume_token(LPAR);
      t = Let();
      jj_consume_token(RPAR);
                                      t = new ASTChoice(t, 0);
      break;
    case SND:
      jj_consume_token(SND);
      jj_consume_token(LPAR);
      t = Let();
      jj_consume_token(RPAR);
                                      t = new ASTChoice(t, 1);
      break;
    case MATCH:
      jj_consume_token(MATCH);
      t2 = Let();
      jj_consume_token(LBRA);
      t = Match(t2);
      break;
    case LABEL:
      n = jj_consume_token(LABEL);
      jj_consume_token(LPAR);
      t = Let();
      jj_consume_token(RPAR);
                                             t = new ASTUnion(n.image, t);
      break;
    case LLABEL:
      n = jj_consume_token(LLABEL);
      jj_consume_token(LPAR);
      t = Let();
      jj_consume_token(RPAR);
                                              t = new ASTLUnion(n.image, t);
      break;
    case SPLIT:
      jj_consume_token(SPLIT);
      t = Let();
      jj_consume_token(LBRA);
      n = jj_consume_token(Id);
      jj_consume_token(VERT);
      n2 = jj_consume_token(Id);
      jj_consume_token(SLIMARROW);
      t2 = Let();
      jj_consume_token(RBRA);
                                                                                         t = new ASTSplit(t, n.image, n2.image, t2);
      break;
    case LPAR:
      jj_consume_token(LPAR);
      t = TermList();
      jj_consume_token(RPAR);
      break;
    case QUESTION:
      jj_consume_token(QUESTION);
      jj_consume_token(LPAR);
      t = Let();
      jj_consume_token(COMMA);
      t2 = Let();
      jj_consume_token(RPAR);
                                                              t = new ASTCheck(t, t2);
      break;
    case QUESTIONTYPES:
      jj_consume_token(QUESTIONTYPES);
      jj_consume_token(LPAR);
      type = Type();
      jj_consume_token(COMMA);
      type2 = Type();
      jj_consume_token(RPAR);
                                                                           t = new ASTCheckTypes(type, type2);
      break;
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
     {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode TermList() throws ParseException {
  ASTNode t, t2;
    t = Let();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
    case VERT:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        t2 = TermCommaList();
                                            t = new ASTPair(t, t2);
        break;
      case VERT:
        jj_consume_token(VERT);
        t2 = TermVertList();
                                           t = new ASTTensor(t, t2);
        break;
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode TermCommaList() throws ParseException {
  ASTNode t, t2;
    t = Let();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      t2 = TermCommaList();
                                            t = new ASTPair(t, t2);
      break;
    default:
      jj_la1[18] = jj_gen;
      ;
    }
    {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode TermVertList() throws ParseException {
  ASTNode t, t2;
    t = Let();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VERT:
      jj_consume_token(VERT);
      t2 = TermVertList();
                                          t = new ASTTensor(t, t2);
      break;
    default:
      jj_la1[19] = jj_gen;
      ;
    }
    {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTNode Match(ASTNode p) throws ParseException {
  Token l, n, n2;
  ASTNode t, e1, e2;
  List<String> labels = new ArrayList<String>();
  List<String> ids = new ArrayList<String>();
  List<ASTNode> exprs = new ArrayList<ASTNode>();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
      l = jj_consume_token(LABEL);
      break;
    case LLABEL:
      l = jj_consume_token(LLABEL);
      break;
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(LPAR);
    n = jj_consume_token(Id);
    jj_consume_token(RPAR);
    jj_consume_token(SLIMARROW);
    e1 = Let();
                                                                                 labels.add(l.image); ids.add(n.image); exprs.add(e1);
    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VERT:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_10;
      }
      jj_consume_token(VERT);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LABEL:
        l = jj_consume_token(LABEL);
        break;
      case LLABEL:
        l = jj_consume_token(LLABEL);
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(LPAR);
      n = jj_consume_token(Id);
      jj_consume_token(RPAR);
      jj_consume_token(SLIMARROW);
      e1 = Let();
                                                                                               if (labels.contains(l.image))
                                              { {if (true) throw new ParseException("duplicate label");} }
                                              else { labels.add(l.image); ids.add(n.image); exprs.add(e1); }
    }
    jj_consume_token(RBRA);
                   t = new ASTMatchUnion(p, labels, ids, exprs);
    {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTType Type() throws ParseException {
  ASTType t1, t2;
    t1 = TypeF();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LOLLIPOP:
    case SLIMARROW:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SLIMARROW:
        jj_consume_token(SLIMARROW);
        t2 = Type();
                                t1 = new ASTTArrow(t1,t2);
        break;
      case LOLLIPOP:
        jj_consume_token(LOLLIPOP);
        t2 = Type();
                               t1 = new ASTTLollipop(t1, t2);
        break;
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
      {if (true) return t1;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTType TypeF() throws ParseException {
  ASTType t, t2;
  Token n;
  TypeBindList ll;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case TINT:
      jj_consume_token(TINT);
                   t = new ASTTInt();
      break;
    case TLINT:
      jj_consume_token(TLINT);
                    t = new ASTTLInt();
      break;
    case Id:
      n = jj_consume_token(Id);
                   t = new ASTTId(n.image);
      break;
    case TBOOL:
      jj_consume_token(TBOOL);
                    t = new ASTTBool();
      break;
    case TLBOOL:
      jj_consume_token(TLBOOL);
                     t = new ASTTLBool();
      break;
    case LRPAR:
      jj_consume_token(LRPAR);
                    t = new ASTTUnit();
      break;
    case TSTRING:
      jj_consume_token(TSTRING);
                      t = new ASTTString();
      break;
    case TUNION:
      jj_consume_token(TUNION);
      jj_consume_token(LBRA);
      ll = LabelList();
      jj_consume_token(RBRA);
                                                    t = new ASTTUnion(ll);
      break;
    case TLUNION:
      jj_consume_token(TLUNION);
      jj_consume_token(LBRA);
      ll = LabelList();
      jj_consume_token(RBRA);
                                                     t = new ASTTLUnion(ll);
      break;
    case LPAR:
      jj_consume_token(LPAR);
      t = TypeList();
      jj_consume_token(RPAR);
      break;
    default:
      jj_la1[25] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
      {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTType TypeList() throws ParseException {
  ASTType t, t2;
    t = Type();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
    case VERT:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case COMMA:
        jj_consume_token(COMMA);
        t2 = TypeCommaList();
                                               t = new ASTTPair(t, t2);
        break;
      case VERT:
        jj_consume_token(VERT);
        t2 = TypeVertList();
                                              t = new ASTTTensor(t, t2);
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    default:
      jj_la1[27] = jj_gen;
      ;
    }
    {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTType TypeCommaList() throws ParseException {
  ASTType t, t2;
    t = Type();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMMA:
      jj_consume_token(COMMA);
      t2 = TypeCommaList();
                                             t = new ASTTPair(t, t2);
      break;
    default:
      jj_la1[28] = jj_gen;
      ;
    }
    {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public ASTType TypeVertList() throws ParseException {
  ASTType t, t2;
    t = Type();
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case VERT:
      jj_consume_token(VERT);
      t2 = TypeVertList();
                                           t = new ASTTTensor(t, t2);
      break;
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    {if (true) return t;}
    throw new Error("Missing return statement in function");
  }

  static final public TypeBindList LabelList() throws ParseException {
  ASTType t;
  HashMap<String, ASTType> ll;
  Token n;
      ll = new HashMap<String, ASTType>() ;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LABEL:
    case LLABEL:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LABEL:
        n = jj_consume_token(LABEL);
        break;
      case LLABEL:
        n = jj_consume_token(LLABEL);
        break;
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(COLON);
      t = Type();
                                                   ll.put(n.image,t);
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case COMMA:
          ;
          break;
        default:
          jj_la1[31] = jj_gen;
          break label_11;
        }
        jj_consume_token(COMMA);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LABEL:
          n = jj_consume_token(LABEL);
          break;
        case LLABEL:
          n = jj_consume_token(LLABEL);
          break;
        default:
          jj_la1[32] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        jj_consume_token(COLON);
        t = Type();
                                                                    if (ll.containsKey(n.image))
                            {{if (true) throw new ParseException("duplicate label");}}
                            else {ll.put(n.image,t);}
      }
      break;
    default:
      jj_la1[33] = jj_gen;
      ;
    }
      {if (true) return new TypeBindList(ll);}
    throw new Error("Missing return statement in function");
  }

  static private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  static private boolean jj_2_2(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_2(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  static private boolean jj_2_3(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_3(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  static private boolean jj_2_4(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_4(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  static private boolean jj_3R_86() {
    if (jj_3R_89()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_90()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_29() {
    if (jj_scan_token(LOLLIPOP)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_28() {
    if (jj_scan_token(SLIMARROW)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_15() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_28()) {
    jj_scanpos = xsp;
    if (jj_3R_29()) return true;
    }
    return false;
  }

  static private boolean jj_3R_12() {
    if (jj_3R_14()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_15()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_84() {
    if (jj_scan_token(VERT)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(58)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) return true;
    }
    if (jj_scan_token(LPAR)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(RPAR)) return true;
    if (jj_scan_token(SLIMARROW)) return true;
    if (jj_3R_76()) return true;
    return false;
  }

  static private boolean jj_3_2() {
    if (jj_scan_token(TYPE)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(EQUAL)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(SEMIC)) return true;
    return false;
  }

  static private boolean jj_3R_83() {
    Token xsp;
    if (jj_3_2()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_2()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_76()) return true;
    return false;
  }

  static private boolean jj_3_1() {
    if (jj_scan_token(LET)) return true;
    if (jj_scan_token(Id)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_91()) jj_scanpos = xsp;
    if (jj_scan_token(EQUAL)) return true;
    if (jj_3R_13()) return true;
    if (jj_scan_token(SEMIC)) return true;
    return false;
  }

  static private boolean jj_3R_82() {
    Token xsp;
    if (jj_3_1()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3_1()) { jj_scanpos = xsp; break; }
    }
    if (jj_3R_76()) return true;
    return false;
  }

  static private boolean jj_3R_81() {
    if (jj_3R_86()) return true;
    return false;
  }

  static private boolean jj_3R_79() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(58)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) return true;
    }
    if (jj_scan_token(LPAR)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(RPAR)) return true;
    if (jj_scan_token(SLIMARROW)) return true;
    if (jj_3R_76()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_84()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(RBRA)) return true;
    return false;
  }

  static private boolean jj_3R_96() {
    if (jj_scan_token(VERT)) return true;
    if (jj_3R_93()) return true;
    return false;
  }

  static private boolean jj_3R_76() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_81()) {
    jj_scanpos = xsp;
    if (jj_3R_82()) {
    jj_scanpos = xsp;
    if (jj_3R_83()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_95() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_92()) return true;
    return false;
  }

  static private boolean jj_3R_93() {
    if (jj_3R_76()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_96()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_88() {
    if (jj_scan_token(VERT)) return true;
    if (jj_3R_93()) return true;
    return false;
  }

  static private boolean jj_3R_87() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_92()) return true;
    return false;
  }

  static private boolean jj_3R_85() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_87()) {
    jj_scanpos = xsp;
    if (jj_3R_88()) return true;
    }
    return false;
  }

  static private boolean jj_3R_92() {
    if (jj_3R_76()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_95()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_80() {
    if (jj_3R_76()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_85()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_78() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_69() {
    if (jj_scan_token(QUESTIONTYPES)) return true;
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_12()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_68() {
    if (jj_scan_token(QUESTION)) return true;
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_67() {
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_80()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_77() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_65() {
    if (jj_scan_token(LLABEL)) return true;
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_66() {
    if (jj_scan_token(SPLIT)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(LBRA)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(VERT)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(SLIMARROW)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RBRA)) return true;
    return false;
  }

  static private boolean jj_3R_64() {
    if (jj_scan_token(LABEL)) return true;
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_63() {
    if (jj_scan_token(MATCH)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(LBRA)) return true;
    if (jj_3R_79()) return true;
    return false;
  }

  static private boolean jj_3R_62() {
    if (jj_scan_token(SND)) return true;
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_61() {
    if (jj_scan_token(FST)) return true;
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_60() {
    if (jj_scan_token(PRINTLN)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_59() {
    if (jj_scan_token(PRINT)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_58() {
    if (jj_scan_token(LFN)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_12()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_78()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(DLOLLIPOP)) return true;
    if (jj_scan_token(LBRA)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RBRA)) return true;
    return false;
  }

  static private boolean jj_3R_57() {
    if (jj_scan_token(FN)) return true;
    if (jj_scan_token(Id)) return true;
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_12()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_77()) { jj_scanpos = xsp; break; }
    }
    if (jj_scan_token(ARROW)) return true;
    if (jj_scan_token(LBRA)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RBRA)) return true;
    return false;
  }

  static private boolean jj_3R_56() {
    if (jj_scan_token(IF)) return true;
    if (jj_3R_13()) return true;
    if (jj_scan_token(LBRA)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RBRA)) return true;
    if (jj_scan_token(ELSE)) return true;
    if (jj_scan_token(LBRA)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RBRA)) return true;
    return false;
  }

  static private boolean jj_3R_55() {
    if (jj_scan_token(NOT)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_54() {
    if (jj_scan_token(MINUS)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_53() {
    if (jj_scan_token(LRPAR)) return true;
    return false;
  }

  static private boolean jj_3R_52() {
    if (jj_scan_token(String)) return true;
    return false;
  }

  static private boolean jj_3R_51() {
    if (jj_scan_token(Id)) return true;
    return false;
  }

  static private boolean jj_3R_50() {
    if (jj_scan_token(LinBool)) return true;
    return false;
  }

  static private boolean jj_3R_49() {
    if (jj_scan_token(Bool)) return true;
    return false;
  }

  static private boolean jj_3R_48() {
    if (jj_scan_token(LinNum)) return true;
    return false;
  }

  static private boolean jj_3R_47() {
    if (jj_scan_token(Num)) return true;
    return false;
  }

  static private boolean jj_3R_43() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_47()) {
    jj_scanpos = xsp;
    if (jj_3R_48()) {
    jj_scanpos = xsp;
    if (jj_3R_49()) {
    jj_scanpos = xsp;
    if (jj_3R_50()) {
    jj_scanpos = xsp;
    if (jj_3R_51()) {
    jj_scanpos = xsp;
    if (jj_3R_52()) {
    jj_scanpos = xsp;
    if (jj_3R_53()) {
    jj_scanpos = xsp;
    if (jj_3R_54()) {
    jj_scanpos = xsp;
    if (jj_3R_55()) {
    jj_scanpos = xsp;
    if (jj_3R_56()) {
    jj_scanpos = xsp;
    if (jj_3R_57()) {
    jj_scanpos = xsp;
    if (jj_3R_58()) {
    jj_scanpos = xsp;
    if (jj_3R_59()) {
    jj_scanpos = xsp;
    if (jj_3R_60()) {
    jj_scanpos = xsp;
    if (jj_3R_61()) {
    jj_scanpos = xsp;
    if (jj_3R_62()) {
    jj_scanpos = xsp;
    if (jj_3R_63()) {
    jj_scanpos = xsp;
    if (jj_3R_64()) {
    jj_scanpos = xsp;
    if (jj_3R_65()) {
    jj_scanpos = xsp;
    if (jj_3R_66()) {
    jj_scanpos = xsp;
    if (jj_3R_67()) {
    jj_scanpos = xsp;
    if (jj_3R_68()) {
    jj_scanpos = xsp;
    if (jj_3R_69()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_71() {
    if (jj_scan_token(DIV)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_73() {
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_76()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_72() {
    if (jj_scan_token(LRPAR)) return true;
    return false;
  }

  static private boolean jj_3R_44() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_70()) {
    jj_scanpos = xsp;
    if (jj_3R_71()) {
    jj_scanpos = xsp;
    if (jj_3R_72()) {
    jj_scanpos = xsp;
    if (jj_3R_73()) return true;
    }
    }
    }
    return false;
  }

  static private boolean jj_3R_70() {
    if (jj_scan_token(STAR)) return true;
    if (jj_3R_43()) return true;
    return false;
  }

  static private boolean jj_3R_38() {
    if (jj_3R_43()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_44()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_39() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(8)) {
    jj_scanpos = xsp;
    if (jj_scan_token(9)) return true;
    }
    if (jj_3R_38()) return true;
    return false;
  }

  static private boolean jj_3R_35() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(28)) {
    jj_scanpos = xsp;
    if (jj_scan_token(29)) {
    jj_scanpos = xsp;
    if (jj_scan_token(30)) {
    jj_scanpos = xsp;
    if (jj_scan_token(31)) {
    jj_scanpos = xsp;
    if (jj_scan_token(32)) {
    jj_scanpos = xsp;
    if (jj_scan_token(33)) return true;
    }
    }
    }
    }
    }
    if (jj_3R_34()) return true;
    return false;
  }

  static private boolean jj_3R_34() {
    if (jj_3R_38()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_39()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_40() {
    if (jj_scan_token(COMMA)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(58)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) return true;
    }
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_31() {
    if (jj_scan_token(AND)) return true;
    if (jj_3R_30()) return true;
    return false;
  }

  static private boolean jj_3R_30() {
    if (jj_3R_34()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_35()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_36() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(58)) {
    jj_scanpos = xsp;
    if (jj_scan_token(59)) return true;
    }
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_12()) return true;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_40()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_32() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_36()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_75() {
    if (jj_scan_token(VERT)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3R_16() {
    if (jj_3R_30()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_31()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3R_17() {
    if (jj_scan_token(OR)) return true;
    if (jj_3R_16()) return true;
    return false;
  }

  static private boolean jj_3R_74() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_45()) return true;
    return false;
  }

  static private boolean jj_3R_42() {
    if (jj_scan_token(VERT)) return true;
    if (jj_3R_46()) return true;
    return false;
  }

  static private boolean jj_3R_46() {
    if (jj_3R_12()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_75()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_41() {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_45()) return true;
    return false;
  }

  static private boolean jj_3R_37() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_41()) {
    jj_scanpos = xsp;
    if (jj_3R_42()) return true;
    }
    return false;
  }

  static private boolean jj_3R_13() {
    if (jj_3R_16()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_17()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  static private boolean jj_3_4() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(QUESTION)) return true;
    return false;
  }

  static private boolean jj_3R_45() {
    if (jj_3R_12()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_74()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3_3() {
    if (jj_3R_12()) return true;
    if (jj_scan_token(QUESTIONTYPES)) return true;
    return false;
  }

  static private boolean jj_3R_99() {
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_33() {
    if (jj_3R_12()) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_37()) jj_scanpos = xsp;
    return false;
  }

  static private boolean jj_3R_27() {
    if (jj_scan_token(LPAR)) return true;
    if (jj_3R_33()) return true;
    if (jj_scan_token(RPAR)) return true;
    return false;
  }

  static private boolean jj_3R_98() {
    if (jj_3R_13()) return true;
    if (jj_scan_token(QUESTION)) return true;
    if (jj_3R_13()) return true;
    return false;
  }

  static private boolean jj_3R_26() {
    if (jj_scan_token(TLUNION)) return true;
    if (jj_scan_token(LBRA)) return true;
    if (jj_3R_32()) return true;
    if (jj_scan_token(RBRA)) return true;
    return false;
  }

  static private boolean jj_3R_25() {
    if (jj_scan_token(TUNION)) return true;
    if (jj_scan_token(LBRA)) return true;
    if (jj_3R_32()) return true;
    if (jj_scan_token(RBRA)) return true;
    return false;
  }

  static private boolean jj_3R_24() {
    if (jj_scan_token(TSTRING)) return true;
    return false;
  }

  static private boolean jj_3R_97() {
    if (jj_3R_12()) return true;
    if (jj_scan_token(QUESTIONTYPES)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_23() {
    if (jj_scan_token(LRPAR)) return true;
    return false;
  }

  static private boolean jj_3R_22() {
    if (jj_scan_token(TLBOOL)) return true;
    return false;
  }

  static private boolean jj_3R_21() {
    if (jj_scan_token(TBOOL)) return true;
    return false;
  }

  static private boolean jj_3R_94() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_97()) {
    jj_scanpos = xsp;
    if (jj_3R_98()) {
    jj_scanpos = xsp;
    if (jj_3R_99()) return true;
    }
    }
    return false;
  }

  static private boolean jj_3R_20() {
    if (jj_scan_token(Id)) return true;
    return false;
  }

  static private boolean jj_3R_19() {
    if (jj_scan_token(TLINT)) return true;
    return false;
  }

  static private boolean jj_3R_90() {
    if (jj_scan_token(SEMIC)) return true;
    if (jj_3R_89()) return true;
    return false;
  }

  static private boolean jj_3R_18() {
    if (jj_scan_token(TINT)) return true;
    return false;
  }

  static private boolean jj_3R_91() {
    if (jj_scan_token(COLON)) return true;
    if (jj_3R_12()) return true;
    return false;
  }

  static private boolean jj_3R_89() {
    if (jj_3R_94()) return true;
    return false;
  }

  static private boolean jj_3R_14() {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_18()) {
    jj_scanpos = xsp;
    if (jj_3R_19()) {
    jj_scanpos = xsp;
    if (jj_3R_20()) {
    jj_scanpos = xsp;
    if (jj_3R_21()) {
    jj_scanpos = xsp;
    if (jj_3R_22()) {
    jj_scanpos = xsp;
    if (jj_3R_23()) {
    jj_scanpos = xsp;
    if (jj_3R_24()) {
    jj_scanpos = xsp;
    if (jj_3R_25()) {
    jj_scanpos = xsp;
    if (jj_3R_26()) {
    jj_scanpos = xsp;
    if (jj_3R_27()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  static private boolean jj_initialized_once = false;
  /** Generated Token Manager. */
  static public ParserTokenManager token_source;
  static SimpleCharStream jj_input_stream;
  /** Current token. */
  static public Token token;
  /** Next token. */
  static public Token jj_nt;
  static private int jj_ntk;
  static private Token jj_scanpos, jj_lastpos;
  static private int jj_la;
  static private int jj_gen;
  static final private int[] jj_la1 = new int[34];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0xc52e1,0x200000,0xc52e0,0x400000,0xc52c0,0x8000000,0x4000000,0xf0000000,0xf0000000,0x300,0x300,0x5c00,0x5c00,0x1000000,0x1000000,0xc52c0,0x3000000,0x3000000,0x1000000,0x2000000,0x0,0x2000000,0x0,0x0,0x0,0x5000,0x3000000,0x3000000,0x1000000,0x2000000,0x0,0x1000000,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0xfdffe1ec,0x0,0xfdffe1ec,0x0,0xfd00e1ec,0x0,0x0,0x3,0x3,0x0,0x0,0x0,0x0,0x0,0x0,0xfd00e1ec,0x0,0x0,0x0,0x0,0xc000000,0x0,0xc000000,0x1800,0x1800,0x20fe0000,0x0,0x0,0x0,0x0,0xc000000,0x0,0xc000000,0xc000000,};
   }
  static final private JJCalls[] jj_2_rtns = new JJCalls[4];
  static private boolean jj_rescan = false;
  static private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser.  ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  static public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new ParserTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  static public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
    if (jj_initialized_once) {
      System.out.println("ERROR: Second call to constructor of static parser. ");
      System.out.println("       You must either use ReInit() or set the JavaCC option STATIC to false");
      System.out.println("       during parser generation.");
      throw new Error();
    }
    jj_initialized_once = true;
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 34; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  static private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  static final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  static private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  static final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  static final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  static private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  static private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  static private int[] jj_expentry;
  static private int jj_kind = -1;
  static private int[] jj_lasttokens = new int[100];
  static private int jj_endpos;

  static private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      boolean exists = false;
      for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        exists = true;
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              exists = false;
              break;
            }
          }
          if (exists) break;
        }
      }
      if (!exists) jj_expentries.add(jj_expentry);
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  static public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[64];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 34; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 64; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  static final public void enable_tracing() {
  }

  /** Disable tracing. */
  static final public void disable_tracing() {
  }

  static private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 4; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
            case 1: jj_3_2(); break;
            case 2: jj_3_3(); break;
            case 3: jj_3_4(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  static private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
