/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package proj.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int Bool = 6;
  /** RegularExpression Id. */
  int LinBool = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int STAR = 10;
  /** RegularExpression Id. */
  int DIV = 11;
  /** RegularExpression Id. */
  int LPAR = 12;
  /** RegularExpression Id. */
  int RPAR = 13;
  /** RegularExpression Id. */
  int LBRA = 14;
  /** RegularExpression Id. */
  int RBRA = 15;
  /** RegularExpression Id. */
  int EQUAL = 16;
  /** RegularExpression Id. */
  int DOT = 17;
  /** RegularExpression Id. */
  int COLON = 18;
  /** RegularExpression Id. */
  int SEMIC = 19;
  /** RegularExpression Id. */
  int TERM = 20;
  /** RegularExpression Id. */
  int COMMA = 21;
  /** RegularExpression Id. */
  int VERT = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int EQ = 25;
  /** RegularExpression Id. */
  int GT = 26;
  /** RegularExpression Id. */
  int LT = 27;
  /** RegularExpression Id. */
  int GTEQ = 28;
  /** RegularExpression Id. */
  int LTEQ = 29;
  /** RegularExpression Id. */
  int DIF = 30;
  /** RegularExpression Id. */
  int NOT = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int ELSE = 33;
  /** RegularExpression Id. */
  int PRINT = 34;
  /** RegularExpression Id. */
  int PRINTLN = 35;
  /** RegularExpression Id. */
  int FN = 36;
  /** RegularExpression Id. */
  int LFN = 37;
  /** RegularExpression Id. */
  int ARROW = 38;
  /** RegularExpression Id. */
  int DLOLLIPOP = 39;
  /** RegularExpression Id. */
  int LOLLIPOP = 40;
  /** RegularExpression Id. */
  int SLIMARROW = 41;
  /** RegularExpression Id. */
  int TENSOR = 42;
  /** RegularExpression Id. */
  int PAIR = 43;
  /** RegularExpression Id. */
  int FST = 44;
  /** RegularExpression Id. */
  int SND = 45;
  /** RegularExpression Id. */
  int MATCH = 46;
  /** RegularExpression Id. */
  int TYPE = 47;
  /** RegularExpression Id. */
  int TINT = 48;
  /** RegularExpression Id. */
  int TUNIT = 49;
  /** RegularExpression Id. */
  int TBOOL = 50;
  /** RegularExpression Id. */
  int TLBOOL = 51;
  /** RegularExpression Id. */
  int TSTRING = 52;
  /** RegularExpression Id. */
  int TUNION = 53;
  /** RegularExpression Id. */
  int TLUNION = 54;
  /** RegularExpression Id. */
  int TTENSOR = 55;
  /** RegularExpression Id. */
  int TPAIR = 56;
  /** RegularExpression Id. */
  int TLINT = 57;
  /** RegularExpression Id. */
  int SPLIT = 58;
  /** RegularExpression Id. */
  int LABEL = 59;
  /** RegularExpression Id. */
  int LLABEL = 60;
  /** RegularExpression Id. */
  int String = 61;
  /** RegularExpression Id. */
  int Id = 62;
  /** RegularExpression Id. */
  int LinNum = 63;
  /** RegularExpression Id. */
  int Num = 64;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"let\"",
    "<Bool>",
    "<LinBool>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"|\"",
    "\"&&\"",
    "\"||\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"~=\"",
    "\"~\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"lfn\"",
    "\"=>\"",
    "\"=o\"",
    "\"-o\"",
    "\"->\"",
    "\"@\"",
    "\"&\"",
    "\"fst\"",
    "\"snd\"",
    "\"match\"",
    "\"type\"",
    "\"int\"",
    "\"()\"",
    "\"bool\"",
    "\"linbool\"",
    "\"string\"",
    "\"union\"",
    "\"linunion\"",
    "\"tensor\"",
    "\"pair\"",
    "\"linint\"",
    "\"split\"",
    "<LABEL>",
    "<LLABEL>",
    "<String>",
    "<Id>",
    "<LinNum>",
    "<Num>",
  };

}
