/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package proj.src.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 5;
  /** RegularExpression Id. */
  int Bool = 6;
  /** RegularExpression Id. */
  int LinBool = 7;
  /** RegularExpression Id. */
  int PLUS = 8;
  /** RegularExpression Id. */
  int MINUS = 9;
  /** RegularExpression Id. */
  int STAR = 10;
  /** RegularExpression Id. */
  int DIV = 11;
  /** RegularExpression Id. */
  int EQ = 12;
  /** RegularExpression Id. */
  int GT = 13;
  /** RegularExpression Id. */
  int LT = 14;
  /** RegularExpression Id. */
  int GTEQ = 15;
  /** RegularExpression Id. */
  int LTEQ = 16;
  /** RegularExpression Id. */
  int DIF = 17;
  /** RegularExpression Id. */
  int AND = 18;
  /** RegularExpression Id. */
  int OR = 19;
  /** RegularExpression Id. */
  int NOT = 20;
  /** RegularExpression Id. */
  int LPAR = 21;
  /** RegularExpression Id. */
  int RPAR = 22;
  /** RegularExpression Id. */
  int LRPAR = 23;
  /** RegularExpression Id. */
  int LBRA = 24;
  /** RegularExpression Id. */
  int RBRA = 25;
  /** RegularExpression Id. */
  int REFL = 26;
  /** RegularExpression Id. */
  int HYP = 27;
  /** RegularExpression Id. */
  int LETEQ = 28;
  /** RegularExpression Id. */
  int NEVER = 29;
  /** RegularExpression Id. */
  int EQUAL = 30;
  /** RegularExpression Id. */
  int VERT = 31;
  /** RegularExpression Id. */
  int DOT = 32;
  /** RegularExpression Id. */
  int COLON = 33;
  /** RegularExpression Id. */
  int SEMIC = 34;
  /** RegularExpression Id. */
  int TERM = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int QUESTION = 37;
  /** RegularExpression Id. */
  int IF = 38;
  /** RegularExpression Id. */
  int ELSE = 39;
  /** RegularExpression Id. */
  int PRINT = 40;
  /** RegularExpression Id. */
  int PRINTLN = 41;
  /** RegularExpression Id. */
  int FN = 42;
  /** RegularExpression Id. */
  int LFN = 43;
  /** RegularExpression Id. */
  int REC = 44;
  /** RegularExpression Id. */
  int ARROW = 45;
  /** RegularExpression Id. */
  int DLOLLIPOP = 46;
  /** RegularExpression Id. */
  int SLIMARROW = 47;
  /** RegularExpression Id. */
  int LOLLIPOP = 48;
  /** RegularExpression Id. */
  int FST = 49;
  /** RegularExpression Id. */
  int SND = 50;
  /** RegularExpression Id. */
  int MATCH = 51;
  /** RegularExpression Id. */
  int SPLIT = 52;
  /** RegularExpression Id. */
  int TYPE = 53;
  /** RegularExpression Id. */
  int TINT = 54;
  /** RegularExpression Id. */
  int TLINT = 55;
  /** RegularExpression Id. */
  int TBOOL = 56;
  /** RegularExpression Id. */
  int TLBOOL = 57;
  /** RegularExpression Id. */
  int TSTRING = 58;
  /** RegularExpression Id. */
  int TUNION = 59;
  /** RegularExpression Id. */
  int TLUNION = 60;
  /** RegularExpression Id. */
  int LABEL = 61;
  /** RegularExpression Id. */
  int LLABEL = 62;
  /** RegularExpression Id. */
  int String = 63;
  /** RegularExpression Id. */
  int Id = 64;
  /** RegularExpression Id. */
  int LinNum = 65;
  /** RegularExpression Id. */
  int Num = 66;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"let\"",
    "<Bool>",
    "<LinBool>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\"()\"",
    "\"{\"",
    "\"}\"",
    "\"refl\"",
    "\"hyp\"",
    "\"leteq\"",
    "\"never\"",
    "\"=\"",
    "\"|\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"?\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"lfn\"",
    "\"rec\"",
    "\"=>\"",
    "\"=o>\"",
    "\"->\"",
    "\"-o>\"",
    "\"fst\"",
    "\"snd\"",
    "\"match\"",
    "\"split\"",
    "\"type\"",
    "\"int\"",
    "\"linint\"",
    "\"bool\"",
    "\"linbool\"",
    "\"string\"",
    "\"union\"",
    "\"linunion\"",
    "<LABEL>",
    "<LLABEL>",
    "<String>",
    "<Id>",
    "<LinNum>",
    "<Num>",
  };

}
