/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package proj.src.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LET = 6;
  /** RegularExpression Id. */
  int Bool = 7;
  /** RegularExpression Id. */
  int LinBool = 8;
  /** RegularExpression Id. */
  int PLUS = 9;
  /** RegularExpression Id. */
  int MINUS = 10;
  /** RegularExpression Id. */
  int STAR = 11;
  /** RegularExpression Id. */
  int DIV = 12;
  /** RegularExpression Id. */
  int EQ = 13;
  /** RegularExpression Id. */
  int GT = 14;
  /** RegularExpression Id. */
  int LT = 15;
  /** RegularExpression Id. */
  int GTEQ = 16;
  /** RegularExpression Id. */
  int LTEQ = 17;
  /** RegularExpression Id. */
  int DIF = 18;
  /** RegularExpression Id. */
  int AND = 19;
  /** RegularExpression Id. */
  int OR = 20;
  /** RegularExpression Id. */
  int NOT = 21;
  /** RegularExpression Id. */
  int LPAR = 22;
  /** RegularExpression Id. */
  int RPAR = 23;
  /** RegularExpression Id. */
  int LRPAR = 24;
  /** RegularExpression Id. */
  int LBRA = 25;
  /** RegularExpression Id. */
  int RBRA = 26;
  /** RegularExpression Id. */
  int REFL = 27;
  /** RegularExpression Id. */
  int HYP = 28;
  /** RegularExpression Id. */
  int LETEQ = 29;
  /** RegularExpression Id. */
  int NEVER = 30;
  /** RegularExpression Id. */
  int EQUAL = 31;
  /** RegularExpression Id. */
  int VERT = 32;
  /** RegularExpression Id. */
  int DOT = 33;
  /** RegularExpression Id. */
  int COLON = 34;
  /** RegularExpression Id. */
  int SEMIC = 35;
  /** RegularExpression Id. */
  int TERM = 36;
  /** RegularExpression Id. */
  int COMMA = 37;
  /** RegularExpression Id. */
  int QUESTION = 38;
  /** RegularExpression Id. */
  int IF = 39;
  /** RegularExpression Id. */
  int ELSE = 40;
  /** RegularExpression Id. */
  int PRINT = 41;
  /** RegularExpression Id. */
  int PRINTLN = 42;
  /** RegularExpression Id. */
  int FN = 43;
  /** RegularExpression Id. */
  int LFN = 44;
  /** RegularExpression Id. */
  int LETREC = 45;
  /** RegularExpression Id. */
  int ARROW = 46;
  /** RegularExpression Id. */
  int DLOLLIPOP = 47;
  /** RegularExpression Id. */
  int SLIMARROW = 48;
  /** RegularExpression Id. */
  int LOLLIPOP = 49;
  /** RegularExpression Id. */
  int FST = 50;
  /** RegularExpression Id. */
  int SND = 51;
  /** RegularExpression Id. */
  int MATCH = 52;
  /** RegularExpression Id. */
  int SPLIT = 53;
  /** RegularExpression Id. */
  int TYPE = 54;
  /** RegularExpression Id. */
  int TINT = 55;
  /** RegularExpression Id. */
  int TLINT = 56;
  /** RegularExpression Id. */
  int TBOOL = 57;
  /** RegularExpression Id. */
  int TLBOOL = 58;
  /** RegularExpression Id. */
  int TSTRING = 59;
  /** RegularExpression Id. */
  int TUNION = 60;
  /** RegularExpression Id. */
  int TLUNION = 61;
  /** RegularExpression Id. */
  int LABEL = 62;
  /** RegularExpression Id. */
  int LLABEL = 63;
  /** RegularExpression Id. */
  int String = 64;
  /** RegularExpression Id. */
  int Id = 65;
  /** RegularExpression Id. */
  int LinNum = 66;
  /** RegularExpression Id. */
  int Num = 67;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 5>",
    "\"let\"",
    "<Bool>",
    "<LinBool>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"&&\"",
    "\"||\"",
    "\"~\"",
    "\"(\"",
    "\")\"",
    "\"()\"",
    "\"{\"",
    "\"}\"",
    "\"refl\"",
    "\"hyp\"",
    "\"leteq\"",
    "\"never\"",
    "\"=\"",
    "\"|\"",
    "\".\"",
    "\":\"",
    "\";\"",
    "\";;\"",
    "\",\"",
    "\"?\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"println\"",
    "\"fn\"",
    "\"lfn\"",
    "\"letrec\"",
    "\"=>\"",
    "\"=o>\"",
    "\"->\"",
    "\"-o>\"",
    "\"fst\"",
    "\"snd\"",
    "\"match\"",
    "\"split\"",
    "\"type\"",
    "\"int\"",
    "\"linint\"",
    "\"bool\"",
    "\"linbool\"",
    "\"string\"",
    "\"union\"",
    "\"linunion\"",
    "<LABEL>",
    "<LLABEL>",
    "<String>",
    "<Id>",
    "<LinNum>",
    "<Num>",
  };

}
